[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/gocardless/pgsql-cluster-manager"
  branch = "master"

[[constraint]]
  name = "github.com/alecthomas/kingpin"
  version = "2.2.6"

[[constraint]]
  name = "github.com/coreos/etcd"
  version = "3.3.3"

[[constraint]]
  name = "github.com/oklog/run"
  version = "1.0.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.4.1"

[[override]]
  source = "https://github.com/fsnotify/fsnotify/archive/v1.4.7.tar.gz"
  name = "gopkg.in/fsnotify.v1"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.9.2"
