---
version: 2

references:
  docker_build_image: &docker_build_image
    working_directory: /go/src/github.com/gocardless/stolon-pgbouncer
    docker:
      - image: &image gocardless/stolon-pgbouncer-circleci:2019040101
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
  docker_postgres_build_image: &docker_postgres_build_image
    working_directory: /go/src/github.com/gocardless/stolon-pgbouncer
    docker:
      - image: *image
        environment:
          PGHOST: "127.0.0.1"
          PGUSER: "postgres"
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
      - image: postgres:11.2
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: ""

jobs:
  build:
    <<: *docker_build_image
    steps:
      - checkout
      - run:
          name: Build test binaries
          command: make bin/stolon-pgbouncer.linux_amd64
      - persist_to_workspace:
          root: /go/src/github.com/gocardless/stolon-pgbouncer
          paths: ['bin/stolon-pgbouncer.linux_amd64']

  unit-integration:
    <<: *docker_postgres_build_image
    steps:
      - checkout
      - run:
          name: Compile ginkgo test suites
          command: ginkgo build -r -race .
      - run:
          name: Run unit tests
          command: find pkg -type f -name '*.test' -printf "%h %f\n" | xargs -n2 sh -c 'cd $0 && su postgres -c ./$1'

  release:
    <<: *docker_build_image
    steps:
      - setup_remote_docker
      - run: echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
      - checkout
      - run:
          name: Release
          command: |
            CURRENT_VERSION="v$(cat VERSION)"

            if [[ $(git tag -l "${CURRENT_VERSION}") == "${CURRENT_VERSION}" ]]; then
              echo "Version ${CURRENT_VERSION} is already released"
              exit 0
            fi

            git tag "${CURRENT_VERSION}"
            git push --tags

            goreleaser --rm-dist

workflows:
  version: 2
  build-integration:
    jobs:
      - unit-integration
      - build
      - release:
          requires:
            - unit-integration
