---
global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/rules.yml

scrape_configs:
  - job_name: "stolon-pgbouncer"
    static_configs:
      - targets: ["pgbouncer:9446"]
  - job_name: "stolon-keeper"
    static_configs:
      - targets:
          - "keeper0:9459"
          - "keeper1:9459"
          - "keeper2:9459"
